#!/usr/bin/env python3
"""Pack Natural Earth land and lake polygons into the SolarOS basemap format.

Natural Earth is public domain, so the world outline ships with SolarOS and
the map needs no tile service, no account, and no network. The 1:110m level
is small enough to live in flash; the finer levels are written for an SD
card.

Lakes come from a second dataset because the land polygons carry almost no
holes: at 1:110m one hole exists in the whole world, so a lake drawn from
the land outline alone would be land. Lake rings are packed after the land
rings and classed as water, and the renderer draws rings in order, so a
lake lands on top of the continent that holds it.

    scripts/build_map_basemap.py --level 110m --c-source \\
        src/services/solar_os_map_basemap_world.c
    scripts/build_map_basemap.py --level 50m --output basemap_50m.bin
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import statistics
import struct
import sys
import urllib.request

SOURCE = ("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
          "master/geojson/ne_{level}_{feature}.geojson")
LEVELS = ("110m", "50m", "10m")
MAGIC = b"SOMB"
VERSION = 2
E7 = 10000000.0
CLASS_SHIFT = 24
CLASS_LAND = 0
CLASS_WATER = 1


def fetch(level: str, feature: str, cache: Path) -> dict:
    cache.mkdir(parents=True, exist_ok=True)
    path = cache / f"ne_{level}_{feature}.geojson"
    if not path.exists():
        url = SOURCE.format(level=level, feature=feature)
        print(f"fetching {url}", file=sys.stderr)
        with urllib.request.urlopen(url, timeout=120) as response:
            path.write_bytes(response.read())
    return json.loads(path.read_text())


def rings(collection: dict) -> list[list[tuple[int, int]]]:
    """Outer rings only: a hole is drawn from the lakes dataset instead."""
    out = []
    for feature in collection["features"]:
        geometry = feature["geometry"]
        polygons = (geometry["coordinates"]
                    if geometry["type"] == "MultiPolygon"
                    else [geometry["coordinates"]])
        for polygon in polygons:
            if not polygon:
                continue
            ring = [(round(lat * E7), round(lon * E7)) for lon, lat in polygon[0]]
            # A closed ring repeats its first point; the renderer closes it.
            if len(ring) > 1 and ring[0] == ring[-1]:
                ring.pop()
            if len(ring) >= 3:
                out.append(ring)
    return out


def simplify(ring: list[tuple[int, int]], tolerance: int) -> list[tuple[int, int]]:
    """Drop vertices closer than the tolerance, in 1e7 degree units."""
    if tolerance <= 0 or len(ring) < 4:
        return ring
    kept = [ring[0]]
    for point in ring[1:]:
        last = kept[-1]
        if abs(point[0] - last[0]) + abs(point[1] - last[1]) >= tolerance:
            kept.append(point)
    return kept if len(kept) >= 3 else ring


def resolution(ring_list: list[tuple[int, list[tuple[int, int]]]]) -> int:
    """Median distance between neighbouring vertices, in hundreds of metres.

    A renderer zoomed in past this is looking at a shape the source never
    claimed to place that precisely, so it can stop believing the outline.
    """
    spans = []
    for _, ring in ring_list:
        for (lat_a, lon_a), (lat_b, lon_b) in zip(ring, ring[1:]):
            d_lat = (lat_b - lat_a) / E7 * 111320.0
            d_lon = ((lon_b - lon_a) / E7 * 111320.0 *
                     math.cos(math.radians((lat_a + lat_b) / 2.0 / E7)))
            span = math.hypot(d_lat, d_lon)
            if span > 0.0:
                spans.append(span)
    if not spans:
        return 0
    return min(65535, round(statistics.median(spans) / 100.0))


def pack(ring_list: list[tuple[int, list[tuple[int, int]]]]) -> bytes:
    points = sum(len(ring) for _, ring in ring_list)
    out = bytearray()
    out += MAGIC
    out += struct.pack("<HHII", VERSION, resolution(ring_list),
                       len(ring_list), points)
    for klass, ring in ring_list:
        out += struct.pack("<I", len(ring) | (klass << CLASS_SHIFT))
    for _, ring in ring_list:
        lats = [lat for lat, _ in ring]
        lons = [lon for _, lon in ring]
        out += struct.pack("<iiii", min(lats), max(lats), min(lons), max(lons))
    for _, ring in ring_list:
        for lat, lon in ring:
            out += struct.pack("<ii", lat, lon)
    return bytes(out)


def c_source(data: bytes, level: str) -> str:
    lines = [
        "/* Generated by scripts/build_map_basemap.py; do not edit. */",
        f"/* Natural Earth 1:{level} land and lakes, public domain. */",
        "",
        '#include "solar_os_map_layers.h"',
        "",
        f"const size_t solar_os_map_basemap_world_size = {len(data)}U;",
        "__attribute__((aligned(4)))",
        "const uint8_t solar_os_map_basemap_world[] = {",
    ]
    for start in range(0, len(data), 16):
        chunk = data[start:start + 16]
        lines.append("    " + " ".join(f"0x{byte:02X}," for byte in chunk))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--level", choices=LEVELS, default="110m")
    parser.add_argument("--tolerance", type=int, default=0,
                        help="drop vertices closer than this, in 1e7 degrees")
    parser.add_argument("--output", type=Path,
                        help="write the packed binary here")
    parser.add_argument("--c-source", type=Path,
                        help="write a C source embedding the binary here")
    parser.add_argument("--no-lakes", dest="lakes", action="store_false",
                        help="pack land only, as releases before lakes did")
    parser.add_argument("--cache", type=Path,
                        default=Path(".cache/natural-earth"))
    args = parser.parse_args()

    if args.output is None and args.c_source is None:
        parser.error("one of --output or --c-source is required")

    features = [("land", CLASS_LAND)]
    if args.lakes:
        features.append(("lakes", CLASS_WATER))
    ring_list = []
    for feature, klass in features:
        packed = [(klass, simplify(ring, args.tolerance))
                  for ring in rings(fetch(args.level, feature, args.cache))]
        print(f"{args.level} {feature}: {len(packed)} rings, "
              f"{sum(len(ring) for _, ring in packed)} points", file=sys.stderr)
        ring_list += packed
    data = pack(ring_list)
    points = sum(len(ring) for _, ring in ring_list)
    print(f"{args.level}: {len(ring_list)} rings, {points} points, "
          f"{len(data)} bytes", file=sys.stderr)

    if args.output is not None:
        args.output.write_bytes(data)
    if args.c_source is not None:
        args.c_source.write_text(c_source(data, args.level))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
